#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server.
# If the number of command-line arguments ($#) is not equal (-ne) to 4, then do something.
if [ $# -ne 4 ]
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    PATH_TO_FILE="$1"
    IP="$2"
    USERNAME="$3"
    PRIVATE_KEY_PATH="$4"
    scp -o StrictHostKeyChecking=no -i "$PRIVATE_KEY_PATH" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
fi
