#!/usr/bin/env bash
# Update the system and install Nginx (if not already installed)

sudo apt-get update
sudo apt-get install -y nginx

Replaceable_chain="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/OUALIID permanent;"
sudo sed -i "s/server_name _;/$Replaceable_chain/" /etc/nginx/sites-enabled/default

sudo service nginx restart
