#!/usr/bin/env bash
# A script that creates a MySQL dump file and creates a zip archive from it.
mysqldump -u root -p${1} --all-databases > backup.sql
tar -czf "$(date +'%d-%m-%Y').tar.gz" backup.sql
