#!/usr/bin/env bash
# Script that displays TCP and UDP listening ports.

IP_ADDRESS="${1}"

fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP_ADDRESS" ];
then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP_ADDRESS}"
fi
