#!/usr/bin/env bash
# The code has been fixed and is back short and sweet.
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx
