#!/usr/bin/env bash
# A Bash script that:
# Creates the file /var/run/myscript.pid containing its PID.
# Displays To infinity and beyond indefinitely.
# Displays I hate the kill command when receiving a SIGTERM signal.
# Displays Y U no love me?! when receiving a SIGINT signal.
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

on_interrupt() {
  echo "Y U no love me?!"
  rm -f /var/run/myscript.pid
  exit 1
}
trap on_interrupt SIGINT SIGTERM
echo $$ > /var/run/myscript.pid
while true;
do
  echo "To infinity and beyond"
  sleep 2
done