#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.


while IFS=: read -r username _ uid _ _ home _;
do
    echo "username $username"
    echo "user id: $uid"
    echo "Home directory path for the user: $home"
done < "/etc/passwd"
