#!/usr/bin/env bash
# Displays the content of the current directory in the form of a list where only the name part is shown after the first hyphen.


for file in *;
do
    if [[ -f "$file" && "$file" != *. ]];
    then
        result=${file#*-}
        echo "$result"
    fi
done